### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by steverobbins** [jimbru/srcds-tools#1]
```
$ ./srctool rcon ***.***.***.*** *********** status
Sending rcon @ ***.***.***.*** (***********): 'status' ...

Connecting to ***.***.***.*** with rcon password of ***********
Traceback (most recent call last):
  File "./bin/rcon.py", line 559, in <module>
    print s.rcon_command(' '.join(args))
  File "./bin/rcon.py", line 223, in rcon_command
    return self._any_rcon_response(command)
  File "./bin/rcon.py", line 196, in _any_rcon_response
    return self._any_rcon_response_hl2(command)[3]
  File "./bin/rcon.py", line 206, in _any_rcon_response_hl2
    result = self.read_packet()
  File "./bin/rcon.py", line 161, in read_packet
    return (packetlen, req_id, command, strs[0], strs[1])    
IndexError: list index out of range
[ ERROR ] 
```

My Python skills are limited so I just changed the line to `return (packetlen, req_id, command, strs[0], '')` and it seems to print half of the full status

This is a TF2 server.

**Comment by jimbru** [comment]
Hey thanks for the issue and pull request! I'm glad someone is actually finding this useful.

I'll merge your PR. If you're successfully using this for a TF2 server, feel free to PR a README update too (I had only ever used it for CS:Source myself).
